# Generated by Django 4.2.11 on 2024-09-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_alter_customuser_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-26 12:35:56', verbose_name='Date de création'),
            preserve_default=False,
        ),
    ]
