# Generated by Django 4.2.11 on 2024-09-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_alter_printer_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printjob',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='file',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='pages',
        ),
        migrations.AddField(
            model_name='printjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminé le'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='copies',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de copies'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fichier à imprimer'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-27 14:14:12', verbose_name='Soumis le'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printjob',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='printers.printer', verbose_name='Imprimante'),
        ),
    ]
