# Generated by Django 4.2.11 on 2024-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0007_customuser_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Soumis le'),
        ),
    ]
